### PR TITLE
Rename unit test and benchmark files

### PR DESCRIPTION
**Pull request by nicksay**

### CODE REVIEW

**Comment by nicksay** [comment]
This changes unit tests from:

```
module1.py
module2.py
tests/test_module1.py
tests/test_module2.py
```

to

```
module1.py
module1_test.py
module2.py
module2_test.py
```

Benchmarks are changed from:

```
tests/benchmark_module.py
```

to

```
tests/module_benchmark.py
```

**Comment by awbraunstein** [comment]
Should benchmarks be in the tests folder? Maybe the folder should be benchmarks/

**Comment by nicksay** [comment]
There's also the https://github.com/nicksay/spitfire/tree/master/tests/perf folder that's currently outside the code tree

**Comment by awbraunstein** [comment]
okay. I'm good with a test folder.

lgtm

**Comment by nicksay** [comment]
So, you're saying create `tests/benchmarks`?

**Comment by awbraunstein** [comment]
yeah. tests/benchmarks sounds good.

**Comment by nicksay** [comment]
Updated with the move:
```
spitfire/runtime/tests/benchmark_filter_function.py
→
tests/benchmarks/filter_function_benchmark.py
```

**Comment by awbraunstein** [comment]
lgtm

**Pull request merged**
